version: '3'

services:
  #DB_Service
  db_service:
    container_name: database_container
    image: mysql:latest
    restart: always
    env_file: ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/data/db
    environment:
      - MYSQL_ROOT_USER=${USERNAME}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}

  app:
    container_name: app_container
    restart: always
    build: .
    ports:
      - 3000:3000
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_HOST: db_service
    depends_on:
      - db_service

  migration:
    container_name: migrator
    build: .
    depends_on:
      - db_service
    command: sh -c 'until nc -z db_service 3306; do sleep 1; done; npx sequelize-cli db:migrate'
